# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-importer" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1732b0231d176fce5f498a426773326e2fad0d9a920c52e9c11c97eabfc3966a"
      url "https://github.com/brian-bell/skills-importer/releases/download/v#{version}/skill-importer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "42529075b72ec0bdc7baf5501f92012d5b7e43c48c2fcd2b2a4b23fc3b97efda"
      url "https://github.com/brian-bell/skills-importer/releases/download/v#{version}/skill-importer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34dd215f462747940a43eb1a4fe7f88d18596b9f549c6762f480faf266bb3c28"
      url "https://github.com/brian-bell/skills-importer/releases/download/v#{version}/skill-importer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf511b19572f40bae1a5bfd440f86c377a0f42a4ff3ccc0d785b512ab87d5777"
      url "https://github.com/brian-bell/skills-importer/releases/download/v#{version}/skill-importer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skill-importer"
  desc "Inspect and manage local AI skill catalogs"
  homepage "https://github.com/brian-bell/skills-importer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-importer"

  # No zap stanza required

  caveats <<~EOS
    The macOS archives are not signed or notarized. If macOS reports that
    skill-importer is damaged or cannot be opened, inspect the installed
    binary and clear quarantine with:

      xattr -dr com.apple.quarantine "$(realpath "$(brew --prefix)/bin/skill-importer")"
  EOS
end
