# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtui" do
  version "0.7.3"

  on_macos do
    on_intel do
      sha256 "f7e34f53ae2a849097a9d382caec17e2783cc87f5b88f7202560779f772b1cb6"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8918cc70c4768faa1a16764acde71b2b9bd43f0f7cba8886298b545dbfd86af4"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9a5e2c4a1618b9e7d1dc42d0241e396fde943ee04baf268fa8a6d10d6ca111d"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edc218dd62d438c5a375da217078d7d6d334f124d46ed6b26c507d5d4dbc4075"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wtui"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/brian-bell/wtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtui"

  # No zap stanza required

end
