# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtui" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "4a25f94d1647cffdc161a27af460bafbaf6f11e000c7cd61bdf0844549bbc261"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "994050e771ab981628160c0a825ac9d4193e78b91de497e68fc50e7e2071d42f"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db03fcf46cf520d0b34baf430126e758f95d00cc21f7dc17621638c3be870f78"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9413d3afaaee289de1488d551f1db1fbdcb73f11a8f3456fe7e8837ed47fee11"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wtui"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/brian-bell/wtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtui"

  # No zap stanza required

end
