# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtui" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "04251b86959e336520dbda7c180c897a443014f78c8cf896e15b00277135951d"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3307715fb5d63820dded067fe09600344b1140298669a25eccca2e8df2190c22"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97106734bea65a3f8ded80f8df1ac2f81ca0f10e27392c570a51b5ec1a61d3f6"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a88ee6eae7a43fedfba2eff97f8cd16d86292758b85832f8588095975dcfa3e"
      url "https://github.com/brian-bell/wtui/releases/download/v#{version}/wtui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wtui"
  desc "Terminal UI for managing git worktrees across repositories"
  homepage "https://github.com/brian-bell/wtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtui"

  # No zap stanza required

end
